{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kyc.ondato",
    "module": "nfc-reader",
    "version": "3.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "nfc-reader-3.2.1.aar",
          "url": "nfc-reader-3.2.1.aar",
          "size": 594664,
          "sha512": "93d83f22362fd88dc95062bdc01f163797de60922fc0a6a74321e50eed6ef51995f74b344ef6c710dbcccb97f38607e6fa966bfe50c2833beaf1a844a0d50451",
          "sha256": "cdab3f661faeb4301a0ae0b8b66af13c05a3228c0a6c9c9280cfb2194a82b142",
          "sha1": "d1cdc87d71edee8860cb8df51b44937703a9d723",
          "md5": "ef796dac560daedf21fbeaa451fb29bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.kyc.ondato",
          "module": "sdk-core",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.07.00"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended"
        },
        {
          "group": "androidx.compose.material3.adaptive",
          "module": "adaptive"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.8.8"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie-compose",
          "version": {
            "requires": "6.6.7"
          }
        },
        {
          "group": "org.jmrtd",
          "module": "jmrtd",
          "version": {
            "requires": "0.7.18"
          }
        },
        {
          "group": "dev.keiji.jp2",
          "module": "jp2-android",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-android",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.github.mhshams",
          "module": "jnbis",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "net.sf.scuba",
          "module": "scuba-sc-android",
          "version": {
            "requires": "0.0.23"
          }
        },
        {
          "group": "org.ejbca.cvc",
          "module": "cert-cvc",
          "version": {
            "requires": "1.4.6"
          }
        },
        {
          "group": "com.madgag.spongycastle",
          "module": "prov",
          "version": {
            "requires": "1.58.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "nfc-reader-3.2.1.aar",
          "url": "nfc-reader-3.2.1.aar",
          "size": 594664,
          "sha512": "93d83f22362fd88dc95062bdc01f163797de60922fc0a6a74321e50eed6ef51995f74b344ef6c710dbcccb97f38607e6fa966bfe50c2833beaf1a844a0d50451",
          "sha256": "cdab3f661faeb4301a0ae0b8b66af13c05a3228c0a6c9c9280cfb2194a82b142",
          "sha1": "d1cdc87d71edee8860cb8df51b44937703a9d723",
          "md5": "ef796dac560daedf21fbeaa451fb29bf"
        }
      ]
    }
  ]
}
